version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "github.com/coreos/ignition"
    - dependency-name: "kubevirt.io/api"
    - dependency-name: "kubevirt.io/client-go"
    - dependency-name: "kubevirt.io/containerized-data-importer-api"
    - dependency-name: "sigs.k8s.io/controller-runtime"
    - dependency-name: "github.com/metal3-io/baremetal-operator/apis"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "v1.3.x"
  ignore:
    - dependency-name: "github.com/coreos/ignition"
    - dependency-name: "kubevirt.io/api"
    - dependency-name: "kubevirt.io/client-go"
    - dependency-name: "kubevirt.io/containerized-data-importer-api"
    - dependency-name: "sigs.k8s.io/controller-runtime"
    - dependency-name: "github.com/metal3-io/baremetal-operator/apis"
  commit-message:
    # Prefix all commit messages with "[v1.3.x]"
    prefix: "[v1.3.x]"
