version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "github.com/coreos/ignition"
    - dependency-name: "kubevirt.io/api"
    - dependency-name: "kubevirt.io/client-go"
    - dependency-name: "kubevirt.io/containerized-data-importer-api"
    - dependency-name: "sigs.k8s.io/controller-runtime"
    - dependency-name: "github.com/metal3-io/baremetal-operator/apis"
    - dependency-name: "github.com/onsi/ginkgo/v2"
      # pin due to golang 1.22
      versions: '>= 2.20.2'
    - dependency-name: "github.com/onsi/gomega"
      # pin due to golang 1.22
      versions: '>= 1.34.2'
    - dependency-name: "github.com/gophercloud/gophercloud"
      # pin due to golang 1.22
      versions: '>= 2.0.0'
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "v1.3.x"
  ignore:
    - dependency-name: "github.com/coreos/ignition"
    - dependency-name: "kubevirt.io/api"
    - dependency-name: "kubevirt.io/client-go"
    - dependency-name: "kubevirt.io/containerized-data-importer-api"
    - dependency-name: "sigs.k8s.io/controller-runtime"
    - dependency-name: "github.com/metal3-io/baremetal-operator/apis"
    - dependency-name: "github.com/onsi/ginkgo/v2"
      # pin due to golang 1.22
      versions: '>= 2.20.2'
    - dependency-name: "github.com/onsi/gomega"
      # pin due to golang 1.22
      versions: '>= 1.34.2'
    - dependency-name: "github.com/gophercloud/gophercloud"
      # pin due to golang 1.22
      versions: '>= 2.0.0'
  commit-message:
    # Prefix all commit messages with "[v1.3.x]"
    prefix: "[v1.3.x]"
