apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: {{ .Network }}-policy
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  mtu: 9000
  nicSelector:
    rootDevices:
    - {{ .SriovRootDevice }}
    pfNames:
    - {{ .SriovPort }}
  nodeSelector:
{{- range $label, $selector := .NodeSriovConfigurationPolicyNodeSelector }}
  {{- if eq $selector "" }}
    {{ $label }}: ""
  {{- else }}
    {{ $label }}: {{ $selector }}
  {{- end }}
{{- end }}
  numVfs: 1
  priority: 5
  resourceName: {{ .Network }}sriovnics