# permissions for end users to view openstackbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackbackup-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackups/status
  verbs:
  - get
