# permissions for end users to view openstackbackuprequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackbackuprequest-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests/status
  verbs:
  - get
