# permissions for end users to edit openstackbackuprequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackbackuprequest-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests/status
  verbs:
  - get
