# permissions for end users to edit provisionservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisionserver-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - provisionservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - provisionservers/status
  verbs:
  - get
