# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackbackuprequests.osp-director.openstack.org
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1beta1", "v1beta2"]
      clientConfig:
        service:
          namespace: openstack
          name: osp-director-operator-controller-manager-service
          path: /convert
