apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  openStackClientImageURL: quay.io/openstack-k8s-operators/tripleo-deploy:latest
  virtualMachineRoles:
    controller:
      roleName: Controller
      roleCount: 0
      cores: 2
      memory: 20
      diskSize: 50
      baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
      storageClass: host-nfs-storageclass
      baseImageVolumeName: openstack-base-img #optional
      networks:
      - ctlplane
