apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackVMSet
metadata:
  name: osp-controller
  namespace: openstack
spec:
  baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
  vmCount: 1
  cores: 2
  memory: 5
  diskSize: 10
  storageClass: host-nfs-storageclass
  #imageImportStorageClass: local #optional
  deploymentSSHSecret: osp-controlplane-ssh-keys
  isTripleoRole: true
  ospNetwork:
    name: osp
    bridgeName: br-osp
    nodeNetworkConfigurationPolicy:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      desiredState:
        interfaces:
        - bridge:
            options:
              stp:
                enabled: false
            port:
            - name: enp6s0
          description: Linux bridge with enp6s0 as a port
          name: br-osp # must be same as bridgeName
          state: up
          type: linux-bridge
  networks:
    - ctlplane
  roleName: Controller
