apiVersion: osp-director.openstack.org/v1beta2
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  openStackClientImageURL: registry.redhat.io/rhosp-rhel8/openstack-tripleoclient:16.2
  openStackClientNetworks:
  - ctlplane
  - external
  - internal_api
  openStackClientStorageClass: host-nfs-storageclass
  openStackRelease: "16.2"
  passwordSecret: userpassword
  virtualMachineRoles:
    controller:
      cores: 6
      ctlplaneInterface: enp2s0
      rootDisk:
        diskSize: 50
        baseImageVolumeName: controller-base-img
        storageClass: host-nfs-storageclass
        storageAccessMode:  ReadWriteMany
        storageVolumeMode: Filesystem
      additionalDisks:
      - name: datadisk1
        diskSize: 1
        storageClass: host-nfs-storageclass
        storageAccessMode:  ReadWriteMany
        storageVolumeMode: Filesystem
      isTripleoRole: true
      memory: 20
      networks:
      - ctlplane
      - external
      - internal_api
      - storage
      - storage_mgmt
      - tenant
      roleCount: 0
      roleName: Controller
