apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackProvisionServer
metadata:
  name: openstackprovisionserver-sample
  namespace: openstack
spec:
  port: 8080
  baseImageUrl: http://192.168.111.1:8080/rhel-guest-image-8.4-825.x86_64.qcow2
