apiVersion: osp-director.openstack.org/v1beta1
kind: ProvisionServer
metadata:
  name: provisionserver-sample
spec:
  # Add fields here
  foo: bar
  port: 8080
  rhelImageUrl: http://10.37.146.224:8080/rhel-guest-image-8.3-417.x86_64.qcow2.gz
