---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: {{ .DomainName }}
  namespace: {{ .Namespace }}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ .Namespace }}/{{ .Network }}
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: {{ .DomainNameUniq }}
      namespace: {{ .Namespace }}
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .DiskSize }}Gi
        volumeMode: Filesystem
        storageClassName: {{ .StorageClass }}
      source:
        pvc:
          name: {{ .BaseImageVolumeName }}
          namespace: {{ .Namespace }}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: {{ .DomainName }}
        openstackvmsets.osp-director.openstack.org/ospcontroller: "True"
    spec:
      domain:
        cpu:
          cores: {{ .Cores }}
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          - bridge: {}
            name: osp
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: ""
        resources:
          requests:
            memory: {{ .Memory }}Gi
      evictionStrategy: LiveMigrate
      hostname: {{ .DomainName }}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name:  {{ .DomainNameUniq }}
        name: rootdisk
      - cloudInitNoCloud:
          secretRef:
            name: {{ .UserDataSecret }}
          networkDataSecretRef:
            name: {{ .NetworkDataSecret }}
        name: cloudinitdisk
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: {{ .Network }}
        name: osp



