apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: {{ .BridgeName }}
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    {{ .DesiredState | nindent 4 }}