apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osp-director-operator-post-install-job-role
rules:
  # Storage version upgrader needs to be able to patch CRDs.
   - apiGroups:
       - "apiextensions.k8s.io"
     resources:
       - "customresourcedefinitions"
       - "customresourcedefinitions/status"
     verbs:
       - "get"
       - "list"
       - "update"
       - "patch"
       - "watch"
  # Our own resources we care about.
   - apiGroups:
        - "osp-director.openstack.org"
     resources:
        - "openstackbackuprequests"
     verbs:
        - "get"
        - "list"
        - "create"
        - "update"
        - "delete"
        - "patch"
        - "watch"