apiVersion: v1
kind: ServiceAccount
metadata:
   name: osp-director-operator-post-install-job
   namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: osp-director-operator-post-install-job-role-binding
subjects:
   - kind: ServiceAccount
     name: osp-director-operator-post-install-job
     namespace: openstack
roleRef:
   kind: ClusterRole
   name: osp-director-operator-post-install-job-role
   apiGroup: rbac.authorization.k8s.io